name: docs_ligandsplitter
channels:

  - conda-forge

  - defaults
dependencies:
    # Base depends
  - python
  - pip
  - ipywidgets
  - Bio
  - MDAnalysis
  - openbabel
  - rdkit
  
  - pydata-sphinx-theme
  - sphinx-design
  - sphinx-copybutton




    # Pip-only installs
  - pip:
    - -e ../
    - rcsb-api

